### ISSUE TITLE
Add New Quotes in Quotes API.

### ISSUE THREAD

**Issue by tanwanimohit** [tanwanimohit/quotesapi#1]
Hello, I know you are eager to earn a hackoctober t-shirt ! this repository will help you to achieve it !

**What you need to do?**

- Just Fork the Repository [Click Here for Tutorial](https://help.github.com/en/articles/fork-a-repo)
Repository Link : [Click Here](https://github.com/tanwanimohit/quotesapi)

- Now just open quotes.db file and scroll down to the end of the file, before `]`

- Now start adding some quotes (2-3 minimum) 

Here is the sample quote format
```
{
    "quote": "Be as you wish to seem.",
    "author": "Socrates"
}
```

**Note : if you are adding multiple quotes don't forget to add the `,` commas** 

That's it !

Just open the PR and i will approve it ASAP. [Click Here for Tutorial](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

Star this repo. and share it with your friends !

Thankyou.

**Comment by izulien** [comment]
Do you prefer with or without category (or have zero preference).

**Comment by tanwanimohit** [comment]
If you are adding category than it ice on the cake, else no worries!
but guys do remember to add commas as it is breaking the code!

**Comment by ongzx** [comment]
#47

**Comment by ongzx** [comment]
#48

**Comment by ansdb** [comment]
I added three quotes into the file, but I'm still waiting for you to approve it?!!!?

**Comment by tanwanimohit** [comment]
> I added three quotes into the file, but I'm still waiting for you to approve it?!!!?

Hello, Thanks for contributions ! because of Conflicts, i merge 4-5 PRs daily, but anyways i have merged your PR.
