### ISSUE TITLE
All special characters were replaced with �.

### ISSUE THREAD

**Issue by izulien** [tanwanimohit/quotesapi#12]
PR 4 has added bad characters to the quotes.db file.  Any special character was replaced with �.

_Originally posted by @izulien in https://github.com/tanwanimohit/quotesapi/pull/4#issuecomment-537604464_

**Comment by tanwanimohit** [comment]
Hello,

Actually he just replaced unwanted character..

**Comment by izulien** [comment]
So you wanted to have � characters instead of - or ' characters?
[image: image.png]
